# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "901b87fa3b7c785895482cc08ff69d2a"
name = "gift"
handle = "gift-31"
application_url = "https://state-daughters-research-demonstrated.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "yanyi-checkout.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://state-daughters-research-demonstrated.trycloudflare.com/auth/callback",
  "https://state-daughters-research-demonstrated.trycloudflare.com/auth/shopify/callback",
  "https://state-daughters-research-demonstrated.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
